# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 10:03
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170419_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=accounts.models.upload_avatar_to, verbose_name='User Profile Picture'),
        ),
    ]
