# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170505_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Required. 100 characters or fewer.', max_length=100, null=True, verbose_name='name'),
        ),
    ]
