apiVersion: v1
kind: ReplicationController
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:
      - name: user-service
        image: inforian/user-service:
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:

